server:
  port: 8080 # El puerto estándar mundial para la puerta de entrada de una API

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        # ----------------------------------------
        # REGLA 1: Tráfico hacia el AUTH-SERVICE
        # ----------------------------------------
        - id: auth-service-route
          # 'lb://' significa Load Balancer. Le decimos: "Busca en Eureka quién se llama AUTH-SERVICE y mándale el tráfico"
          uri: lb://AUTH-SERVICE
          predicates:
            # Si la URL que pide el cliente empieza por alguna de estas, aplica esta regla
            - Path=/api/auth/**, /api/test/**