server:
  port: 8080 # El puerto estándar mundial para la puerta de entrada de una API

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        # Tráfico hacia el AUTH-SERVICE
        - id: auth-service-route
          # 'lb://' significa Load Balancer. Le decimos: "Busca en Eureka quién se llama AUTH-SERVICE y mándale el tráfico"
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        # RUTA PARA VUELOS:
        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/api/flights/**

        # RUTA PARA RESERVAS:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**