spring.application.name=config-server

server.port=8888
spring.cloud.config.server.native.search-locations=file:///D:/Proyectos/airlines-gds-system/config
spring.profiles.active=native
spring.main.allow-bean-definition-overriding=true